Update next/yjs/slate example
liveblocks/liveblocks pull request #1043
Opened 2023-08-03 15:14 UTC by adamyonk

Added some details for setting up yjs/slate with the older Next /pages/api routes

2023-08-03 19:01 UTC, CTNicholas requested changes

2023-08-03 19:02 UTC, CTNicholas commented
Excellent changes, thank you for leaving a PR for us! 😄 Would you mind applying my changes?

2023-08-03 19:09 UTC, CTNicholas approved these changes

2023-08-03 19:09 UTC, merged

2023-08-04 05:08 UTC, adamyonk commented
Glad to help!