Upgrade starter kit to `/app`
liveblocks/liveblocks pull request #1538
Opened 2024-03-20 13:17 UTC by CTNicholas

**TODO**
- [ ] Pagination
- [ ] Groups on dashboard
- [ ] Share menu
- [ ] Notifications
- [ ] Tidy and restructure
- [ ] Delete old starter kit

2024-04-03 13:47 UTC, marcbouchenoire requested changes
Nice! 🥳 I left a few comments, only small things.

2024-04-03 13:47 UTC, marcbouchenoire commented on starter-kits/nextjs-starter-kit/auth.ts
> +  secret: NEXTAUTH_SECRET || "p49RDzU36fidumaF7imGnzyhRSPWoffNjDOleU77SM4=",
Maybe a comment to explain the fallback value?

2024-04-03 13:47 UTC, marcbouchenoire commented on starter-kits/nextjs-starter-kit/primitives/Popover/Popover.module.css
> -  overflow: hidden;
Copy-paste conflict, this was added in https://github.com/liveblocks/liveblocks/pull/1437 and shouldn't be removed.

2024-04-03 13:47 UTC, marcbouchenoire commented on starter-kits/nextjs-starter-kit/liveblocks.server.config.ts
> +"server-only";
Does that work? I thought it was a separate package (`import "server-only"`).

2024-04-04 14:02 UTC, CTNicholas commented
Thanks for the recommendations @marcbouchenoire! Implemented them.

2024-04-04 15:32 UTC, marcbouchenoire approved these changes

2024-04-17 11:44 UTC, merged