Advanced avatars and cursors examples
liveblocks/liveblocks pull request #365
Opened 2022-06-24 12:47 UTC by CTNicholas

## Info
I've added two advanced Next.js examples to the repo, one for _live cursors_ and one for _live avatars_. These two examples use `framer-motion` to create smoother animations.

### `nextjs-live-avatars-advanced`
Contains a spring-animated avatar stack, and also a reusable `Avatar` component, allowing for multiple types of avatars.

### `nextjs-live-cursors-advanced`
Contains spring-animated live cursors, and also a reusable `LiveCursors` component that allows you to pass it a cursor panel (React `ref` containing an element). From there it will accurately calculate cursor positions from the element's scroll position, the position of the element on the page etc.

_To be released after our new examples page is ready_

2022-06-28 08:00 UTC, marcbouchenoire commented on examples/nextjs-live-avatars-advanced/pages/api/auth.ts
> +}
URLs need to be updated.

2022-06-28 08:00 UTC, marcbouchenoire commented on examples/nextjs-live-avatars-advanced/pages/index.tsx
> +      `Learn more: https://github.com/liveblocks/liveblocks/tree/main/examples/nextjs-live-cursors#getting-started.`;
URLs need to be updated.

2022-06-28 12:19 UTC, CTNicholas commented
Forgot to remove the unnecessary assets—done.

2022-06-30 15:47 UTC, marcbouchenoire requested changes
There's a few small things that I didn't catch during the first review, sorry about that!

And also there's an unused overlap regarding the utils like `useBoundingClientRectRef.ts` that is probably a remnant of the single version example.

2022-06-30 15:47 UTC, marcbouchenoire commented on examples/nextjs-live-avatars-advanced/README.md
> +After forking [this example](https://codesandbox.io/s/github/liveblocks/liveblocks/tree/main/examples/nextjs-live-avatars) on CodeSandbox, create the `LIVEBLOCKS_SECRET_KEY` environment variable as a
```suggestion
After forking [this example](https://codesandbox.io/s/github/liveblocks/liveblocks/tree/main/examples/nextjs-live-avatars-advanced) on CodeSandbox, create the `LIVEBLOCKS_SECRET_KEY` environment variable as a [secret](https://codesandbox.io/docs/secrets).
```

2022-06-30 15:47 UTC, marcbouchenoire commented on examples/nextjs-live-avatars-advanced/pages/index.tsx
> +}
Since this example is using a private key and there's already a warning in `auth.ts` we can remove this.

2022-06-30 15:47 UTC, marcbouchenoire commented on examples/nextjs-live-cursors-advanced/pages/api/auth.ts
> +  // See https://liveblocks.io/docs/api-reference/liveblocks-node#authorize for more information
We can probably remove this.

2022-06-30 15:47 UTC, marcbouchenoire commented on examples/nextjs-live-cursors-advanced/pages/index.tsx
> +}
Since this example is using a private key and there's already a warning in `auth.ts` we can remove this.

2022-06-30 15:47 UTC, marcbouchenoire commented on examples/nextjs-live-avatars-advanced/styles/globals.css
> +  font-family: "Inter", -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
```suggestion
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
```

2022-06-30 15:47 UTC, marcbouchenoire commented on examples/nextjs-live-cursors-advanced/styles/globals.css
> +  font-family: "Inter", -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
```suggestion
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
```

2022-07-11 09:33 UTC, marcbouchenoire approved these changes
🥳

2022-08-09 16:55 UTC, GuillaumeSalles approved these changes

2022-08-17 12:05 UTC, merged