Convert react dashboard
liveblocks/liveblocks pull request #842
Opened 2023-04-26 06:19 UTC by taylorpwhipp

This PR converts the `react-dashboard` example to Typescript with Next.js.  

The existing react-dashboard will need to be updated to nextjs-dashboard in liveblocsk.io.
PR here:

2023-04-26 06:45 UTC, nvie reviewed
As I mentioned to Taylor in private DM already, I'll skip this review today, but I may review this in hindsight when I'm back in office next week.

2023-04-26 11:28 UTC, CTNicholas requested changes
Great work, basically just a couple of changes to the types and we're there 😄 

I've send a short video message on Slack with a proper explanation about the improvements we can make! Would advise taking a look before checking the review

2023-04-26 11:28 UTC, CTNicholas commented on examples/nextjs-dashboard/src/components/Card.tsx
> +            y={(presence.cursor as CursorPosition).y * boundingRect.height}
We can remove `as` here

2023-04-26 11:28 UTC, CTNicholas commented on examples/nextjs-dashboard/pages/index.tsx
> +      (myPresence.selectedDataset as SelectedDataset)?.dataKey === dataKey
We can remove `as` here (see my Slack DM)

2023-04-26 11:28 UTC, CTNicholas commented on examples/nextjs-dashboard/pages/index.tsx
> +        (selectedDataset as SelectedDataset)?.dataKey === dataKey
We can remove `as` here

2023-04-26 11:28 UTC, CTNicholas commented on examples/nextjs-dashboard/pages/_app.tsx
> +        selectedDataset: { cardId: null, dataKey: null },
```suggestion
        selectedDataset: null,
```

We can make this `null` initially (see I changed the type in `liveblocks.config.ts`)

2023-04-26 11:28 UTC, CTNicholas commented on examples/nextjs-dashboard/pages/index.tsx
> +};
```suggestion
```

After removing `as`, we no longer need this 😄

2023-04-26 11:28 UTC, CTNicholas commented on examples/nextjs-dashboard/src/liveblocks.config.ts
> +export type CursorPosition = {
```suggestion
type CursorPosition = {
```
After changes we don't need to export this anymore

2023-04-26 11:28 UTC, CTNicholas commented on examples/nextjs-dashboard/src/liveblocks.config.ts
> +export type Presence = {
```suggestion
type Presence = {
```
After changes we don't need to export this anymore

2023-04-27 09:49 UTC, CTNicholas approved these changes
Good to go!

2023-04-27 22:12 UTC, merged